{% set name = "liknorm-py" %}
{% set version = "1.0.4" %}
{% set sha256 = "6c7454265f8bc800882836aeb1d8a18a1cc4fd7bf295269e5ee21b2904dc5b10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win32 or (win and py<35)]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - cffi >=1.7
    - toolchain
    - liknorm >=1.2.3
  run:
    - python
    - cffi >=1.7
    - liknorm >=1.2.3
    - numpy >=1.9

test:
  requires:
    - pytest >=3
  imports:
    - liknorm
  commands:
    - python -c "import sys; import liknorm; sys.exit(liknorm.test())"

about:
  home: https://github.com/limix/liknorm-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Liknorm Python wrapper'
  dev_url: https://github.com/limix/liknorm-py

extra:
  recipe-maintainers:
    - Horta
